### ISSUE TITLE
Doesn't work in node 20.8.0 to 20.x

### ISSUE THREAD

**Issue by desclapez** [Xunnamius/next-test-api-route-handler#910]
<details open><summary><strong>The problem</strong></summary>

In a project using node 20.8+ (20.8.0, 20.8.1, 20.9.0...), using node 20 as major, minor 8 and up. Gives the following error:
```
Error: next-test-api-route-handler (NTARH) failed to import api-utils.js

  This is usually caused by:

    1. Using npm@<7 and/or node@<15, which doesn't install peer deps automatically (review install instructions)
    2. NTARH and the version of Next.js you installed are actually incompatible (please submit a bug report)

  Failed import attempts:

    - EBADF: bad file descriptor, fstat
    - Cannot find module 'next/dist/server/api-utils.js'
    - Cannot find module 'next/dist/next-server/server/api-utils.js'
    - Cannot find module 'next-server/dist/server/api-utils.js'

    at y (/<repo_path>/node_modules/next-test-api-route-handler/dist/index.js:71:38)
    at async Object.<anonymous> (<repo_path>/src/modules/portal/api/downloadExamPdf.test.ts:44:5)
```

I didn't try in other OS, just Macosx Ventura.

Seems working with no problem in 20.7.0

</details>

<details><summary><strong>Reproduction steps</strong></summary>
In a basic next project, using jest and next-test-api-route-handler:

- With node 20.8.0 execute an api handler test
</details>

<details><summary><strong>Additional context</strong></summary>

- OS: Macosx Ventura
- Node version: 20.8.0
- TypeScript: yes, version 5.2.0

Relevant log lines:
```
(super long error log lines pasted here)
```

</details>

**Comment by Xunnamius** [comment]
This is interesting, because the Actions tests are still passing with node@20.x. I'll investigate this today.

**Comment by Xunnamius** [comment]
@desclapez Hmm, I can't seem to reproduce this on Linux (Ubuntu) using nodesource's 20.9.0 or Windows (Windows 10) using 18.18.2.

That `EBADF: bad file descriptor, fstat` as the first error in the list is telling. [Stackoverflow](https://stackoverflow.com/questions/16604176/error-ebadf-bad-file-descriptor-when-running-node-using-nohup-of-forever) suggests this could be due to your Node runtime environment. Perhaps you're using some non-standard environment variables? [These](https://github.com/Nexus-Mods/Vortex/issues/4709) [issues](https://github.com/nodejs/node-v0.x-archive/issues/1189) suggests that it's not a Node issue at all but an underlying filesystem/OS problem.

Do you have a different system you could run your tests on?

**Comment by desclapez** [comment]
Hi @Xunnamius, regarding my operating system, is Macosx Ventura, version 13.0. The hardware is an Apple M1 Pro Max. I've tried in another Macosx Ventura, version 13.6, running on an Apple M1 Pro Max and the result is the same.


Since I do not have another machine/s right now, I've tried the following using docker in my Apple laptop
- In ubuntu 20 and ubuntu 22 containers I have same results I've post in my first comment.

- Then I've tried to clone this repo and tried to install in both OS (macosx ventura and ubuntu 20/22), but all them failed in the `npm ci` step with the following error:
```
root@6320e42390c9:/var/local/next-test-api-route-handler# npm ci
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @ergodark/types@1.0.17: this package has been superseded by @xunnamius/types
npm WARN tarball tarball data for semantic-release@https://xunn.at/semantic-release-atam (sha512-ClfsCGVF9IBrmQLJPGuaXw9+7R8KANo8r68NC/hSZpcVtl52RTuUgnLrFAmenu7nE5O9FpXd6reJdp2aueDzgQ==) seems to be corrupted. Trying again.
npm notice 
npm notice New minor version of npm available! 10.1.0 -> 10.2.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.2
npm notice Run npm install -g npm@10.2.2 to update!
npm notice 
npm ERR! code EINTEGRITY
npm ERR! sha512-ClfsCGVF9IBrmQLJPGuaXw9+7R8KANo8r68NC/hSZpcVtl52RTuUgnLrFAmenu7nE5O9FpXd6reJdp2aueDzgQ== integrity checksum failed when using sha512: wanted sha512-ClfsCGVF9IBrmQLJPGuaXw9+7R8KANo8r68NC/hSZpcVtl52RTuUgnLrFAmenu7nE5O9FpXd6reJdp2aueDzgQ== but got sha512-DHyVFdPSQLK6qwAdcsUqCmikH3+E1FjAT9Z9vb4iktOac0fRvgDvZV4MCGknqaXZ6+BB7aq5AaCnjs6dQ9gjuQ==. (425956 bytes)

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-01T21_56_51_274Z-debug-0.log
```

**Comment by desclapez** [comment]
>  I can't seem to reproduce this on Linux (Ubuntu) using node 20.5.1 or 20.9.0 or Windows (Windows 10) using 18.18.2.

Btw I'm curious about the node version used in github actions, since it says 20.x but I would like to see in any log the actual current version being used (how that 20.x is being resolved), could you point me to it please? :)

**Comment by Xunnamius** [comment]
> Btw I'm curious about the node version used in github actions, since it says 20.x but I would like to see in any log the actual current version being used (how that 20.x is being resolved), could you point me to it please? :)

You can see the specific node version selected [here](https://github.com/Xunnamius/next-test-api-route-handler/actions/runs/6725983158/job/18281419602#step:4:11). Don't mind the 21.x test.

I attempted to reproduce your result on my local machines using 20.5.1, 20.9.0, and 18.18.2.

**Comment by desclapez** [comment]
Ok I think I found the issue, the tests failing had a problem because the 'fs' module was being mocked in a non proper way, looks that someone put the code there to mock the whole node_modules folder... 🤦🏻 

So I'm sorting that now, sorry for the inconvenience :)

This can be closed

**Comment by Xunnamius** [comment]
Ah, yeah, mocking fs too deeply can get pretty gnarly in my experience. No problem and thanks for investigating :)
