### ISSUE TITLE
Cannot find module 'next/dist/next-server/server/api-utils.js' from 'node_modules/next-test-api-route-handler/dist/index.js'

### ISSUE THREAD

**Issue by willnix86** [Xunnamius/next-test-api-route-handler#320]
<details open><summary><strong>The problem</strong></summary>

Using Next 11.0.1 and NTARH 2.0.1, when running tests I receive the following error:

```Cannot find module 'next/dist/next-server/server/api-utils.js' from 'node_modules/next-test-api-route-handler/dist/index.js'```

If I look in the next node_modules folder, the correct path is 'next/dist/server/api-utils.js'

</details>

**Comment by Xunnamius** [comment]
Ah, yeah, the NextJS devs have the api-utils in four different locations across several versions 😅.  This should be accounted for in the latest version of NTARH (v2.2.1). If you are able to update, does the problem go away?

**Comment by willnix86** [comment]
So if I update, I end up with a bunch of errors saying that ‘undefined’ should be string value or Array Buffer, or something like that. Can’t remember off the top of my head - for now, I just reverted to Next 11.0.1 and everything works fine!


Will Nixon
Software Developer
310-463-0567
willnixon.dev <https://www.willnixon.dev/>

Lemmi - the app that lets you chat <https://www.lemmichat.com/>

**Comment by Xunnamius** [comment]
Just to be sure: I meant only update NTARH, not NextJS. The latest NTARH should work with the older NextJS v11.0.x (integration tests are passing at least).

**Comment by willnix86** [comment]
So, updating to 2.2.1 gives me this error:

```    TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined

      at ServerResponse.apiRes.end (node_modules/next/server/api-utils.ts:77:33)
      at onerror (node_modules/next-connect/dist/index.cjs:4:47)
      at node_modules/next-connect/dist/index.cjs:16:16
      at apiResolver (node_modules/next/dist/server/api-utils.js:101:9)```

**Comment by Xunnamius** [comment]
Interesting, this seems like the NextJS resolver function itself might have a problem with your handler, since NTARH doesn't call `res.end` (only your handler does). 

First, does your handler code run in NextJS normally without errors? 

Second, can you show me the code around your usage of the `testApiHandler` function and the handler you're testing? Or better yet, if you can spin up a tiny dummy repo that reproduces your error, I can pinpoint the problem 🙂
